(function () {
  function createId() {
    return "p" + Date.now().toString(16) + "" + Math.floor(Math.random() * 9999);
  }

  window.products = [
    {
      id: createId(),
      name: "Café Molido Premium",
      description: "Café 100% arábica con aroma intenso y sabor equilibrado. Ideal para prensa francesa o cafetera.",
      category: "Bebidas",
      status: "active",
      price: 6.5,
      stock: 25,
      imageUrl: "https://productosmockatto.com/cdn/shop/files/CF_1K.png?v=1749139240",
      createdAt: new Date().toISOString(),
    },
    {
      id: createId(), 
      name: "Té Verde Orgánico",
      description: "Té verde natural con antioxidantes. Perfecto para una bebida saludable durante el día.",
      category: "Bebidas",
      status: "active",
      price: 4.25,
      stock: 40,
      imageUrl: "https://twinings.mx/cdn/shop/products/29-te-verde-organico_edb06146-4f7a-47c1-ad20-4f68a29b4acc_800x.png?v=1661196834",
      createdAt: new Date().toISOString(),
    },
    {
      id: createId(),
      name: "Botella Térmica",
      description: "Botella térmica de acero inoxidable que mantiene bebidas calientes o frías por horas.",
      category: "Bebidas",
      status: "active",
      price: 9.75,
      stock: 35,
      imageUrl: "https://numadabrand.com/wp-content/uploads/2022/05/2024_BOTELLA-TERMICA_600ML_NUMADA_CERAMIC-negro_1-600x600-optimized.png",
      createdAt: new Date().toISOString(),
    },
    {
      id: createId(),
      name: "Chocolate",
      description: "Mezcla de cacao premium para preparar chocolate caliente cremoso en minutos.",
      category: "Bebidas",
      status: "active",
      price: 3.90,
      stock: 60,
      imageUrl: "https://www.fralia.com.br/media/2025/01/chocolate-32.png",
      createdAt: new Date().toISOString(),
    },
    {
      id: createId(),
      name: "Audífonos Inalámbricos",
      description: "Audífonos Bluetooth con batería de larga duración y sonido envolvente.",
      category: "Electrónica",
      status: "active",
      price: 39.99,
      stock: 12,
      imageUrl: "https://static.vecteezy.com/system/resources/thumbnails/024/558/883/small/black-wireless-headphones-isolated-on-transparent-background-ai-generated-png.png",
      createdAt: new Date().toISOString(),
    },
    {
      id: createId(),
      name: "Mouse Gamer RGB",
      description: "Mouse gamer con iluminación RGB y sensor de alta precisión.",
      category: "Electrónica",
      status: "active",
      price: 15.99,
      stock: 28,
      imageUrl: "https://redragon.es/content/uploads/2021/04/GRIFFIN-B.png",
      createdAt: new Date().toISOString(),
    },
    {
      id: createId(),
      name: "Teclado Mecánico",
      description: "Teclado mecánico con switches suaves y retroiluminación LED.",
      category: "Electrónica",
      status: "active",
      price: 45.5,
      stock: 15,
      imageUrl: "https://apizd.zonadigitalsv.com/storage/productos/kFeWMHs0oBodW3PwLrWAYRHTKwt5RD8tTZ0NnC59.png",
      createdAt: new Date().toISOString(),
    },
    {
      id: createId(),
      name: "Cargador USB Rápido",
      description: "Cargador USB con tecnología de carga rápida compatible con múltiples dispositivos.",
      category: "Electrónica",
      status: "active",
      price: 8.99,
      stock: 50,
      imageUrl: "https://tiendavirtual.viva.com.do/cdn/shop/files/image-removebg-preview-2024-09-27T094006.006.png?v=1749762504",
      createdAt: new Date().toISOString(),
    },
    {
      id: createId(),
      name: "Memoria USB 64GB",
      description: "Memoria USB portátil de alta velocidad para almacenamiento seguro de archivos.",
      category: "Electrónica",
      status: "active",
      price: 12.5,
      stock: 45,
      imageUrl: "https://compushopsv.com/cdn/shop/files/Memoria-USB-64GB-Exodia-M3.2-Kingston-Morado-KC-U2L64-7LP.png?v=1712954040",
      createdAt: new Date().toISOString(),
    },
    {
      id: createId(),
      name: "Soporte para Laptop",
      description: "Soporte ergonómico ajustable para mejorar la postura al trabajar con laptop.",
      category: "Electrónica",
      status: "active",
      price: 18.3,
      stock: 20,
      imageUrl: "https://computodo.com.sv/wp-content/uploads/2025/03/Klip-Xtreme-Docking-Station.png",
      createdAt: new Date().toISOString(),
    },

    {
      id: createId(),
      name: "Cuaderno Profesional",
      description: "Cuaderno con tapa dura y hojas rayadas ideal para estudio o trabajo.",
      category: "Papelería",
      status: "active",
      price: 2.25,
      stock: 80,
      imageUrl: "https://unionpapelera.com.mx/wp-content/uploads/2024/08/04635_1.png",
      createdAt: new Date().toISOString(),
    },
    {
      id: createId(),
      name: "Agenda Ejecutiva",
      description: "Agenda con diseño elegante para organizar tareas y reuniones.",
      category: "Papelería",
      status: "active",
      price: 7.9,
      stock: 30,
      imageUrl: "https://danpex.com.mx/wp-content/uploads/2019/09/AS248O-26-NE-2.png",
      createdAt: new Date().toISOString(),
    },
    {
      id: createId(),
      name: "Set de Resaltadores",
      description: "Paquete de 6 resaltadores fluorescentes para estudiar o trabajar.",
      category: "Papelería",
      status: "active",
      price: 3.2,
      stock: 90,
      imageUrl: "https://multimarcas.com.bo/storage/images/productos/1363-0-1651610941.png",
      createdAt: new Date().toISOString(),
    },
    {
      id: createId(),
      name: "Bolígrafos Gel",
      description: "Set de bolígrafos de tinta gel de escritura suave y precisa.",
      category: "Papelería",
      status: "active",
      price: 2.8,
      stock: 100,
      imageUrl: "https://www.propapel.mx/image/cache/catalog/Papeleria/507171_big_a-1000x1000.png",
      createdAt: new Date().toISOString(),
    },
    {
      id: createId(),
      name: "Carpeta Organizadora",
      description: "Carpeta con múltiples compartimentos para organizar documentos.",
      category: "Papelería",
      status: "active",
      price: 5.4,
      stock: 55,
      imageUrl: "https://cdn.asi.do/qj53ywjy4niwbgmjl2ueuxahm39r",
      createdAt: new Date().toISOString(),
    },

    {
      id: createId(),
      name: "Mochila Ejecutiva",
      description: "Mochila resistente con compartimento acolchado para laptop.",
      category: "Accesorios",
      status: "active",
      price: 29.99,
      stock: 18,
      imageUrl: "https://www.mygreywolf.com/cdn/shop/files/aoking_business_backpack_sn2119_blk_front_view.webp?v=1715129758",
      createdAt: new Date().toISOString(),
    },
    {
      id: createId(),
      name: "Funda para Laptop",
      description: "Funda acolchada para proteger laptops de golpes y rayones.",
      category: "Accesorios",
      status: "active",
      price: 14.5,
      stock: 40,
      imageUrl: "https://apizd.zonadigitalsv.com/storage/productos/zsC5xhAYrpNE7yQIUOBVbdKkOPwyJ8Gu4ttW9YeA.png",
      createdAt: new Date().toISOString(),
    },
    {
      id: createId(),
      name: "Mouse Pad Antideslizante",
      description: "Mouse pad con superficie suave y base antideslizante.",
      category: "Accesorios",
      status: "active",
      price: 4.2,
      stock: 75,
      imageUrl: "https://reset.net.co/wp-content/uploads/2021/02/Pad-Mouse-Pure-Black-Post.webp",
      createdAt: new Date().toISOString(),
    },
    {
      id: createId(),
      name: "Llavero Multifunción",
      description: "Llavero compacto con pequeñas herramientas útiles para el día a día.",
      category: "Accesorios",
      status: "active",
      price: 3.5,
      stock: 120,
      imageUrl: "https://www.crealo.es/21692-large_default/llavero-multifuncional-de-abs-notouchit-personalizado.jpg",
      createdAt: new Date().toISOString(),
    },
    {
      id: createId(),
      name: "Organizador de Escritorio",
      description: "Organizador de escritorio con compartimentos para lápices, notas y accesorios.",
      category: "Accesorios",
      status: "active",
      price: 6.8,
      stock: 45,
      imageUrl: "https://librerialapaloma.cl/wp-content/uploads/2024/08/organizador-de-escritorio-metal-952-otimo-3.png",
      createdAt: new Date().toISOString(),
    },
  ];

  window.createProductId = createId;
})();